#!/bin/tcsh
# Generated by cmake 
setenv JUNO_OFFLINE_VERSION J..20250415-g4aab2b7
setenv CMAKE_PREFIX_PATH /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/InstallArea:${CMAKE_PREFIX_PATH}
setenv PATH /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/InstallArea/bin:${PATH}
setenv LD_LIBRARY_PATH /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/InstallArea/lib64:${LD_LIBRARY_PATH}
setenv PYTHONPATH /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/InstallArea/lib64:${PYTHONPATH}
setenv PYTHONPATH /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/InstallArea/python:${PYTHONPATH}

setenv JUNOSTARTERROOT /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/JUNOStarter
setenv JUNOSTARTERESDROOT /datafs/users/wujxy/waterphase_analysis/realdata_analysis/juno_analysis/juno-starter/JUNOStarterESD

# Additional Environment Variables creating using SETENV 
